import pytest

from abi.errors import ToolError
from abi.exporters import NextflowExporter
from abi.plugins import get_plugin


def test_nextflow_exporter_renders_processes_from_abi_plan(tmp_path):
    plugin = get_plugin("metatranscriptomics")
    config = plugin.load_config(
        overrides={
            "outdir": str(tmp_path / "results"),
            "log_dir": str(tmp_path / "log"),
        }
    )
    plan = plugin.build_plan(config)

    script = NextflowExporter().export(plan, config, plugin.registry())

    assert "nextflow.enable.dsl=2" in script
    assert "process RNA1_QC_FASTP" in script
    assert "process RNA1_ALIGNMENT_STAR" in script
    assert "process RNA1_EXPRESSION_FEATURECOUNTS" in script
    assert "fastp -i" in script
    assert "/examples/fixtures/tiny_R1.fastq" in script
    assert "STAR --runThreadN 4" in script
    assert 'featureCounts -T "$1" -p' in script
    assert "retrying featureCounts without -p" in script
    assert "workflow {" in script
    assert "abi_root = Channel.value('abi_nextflow_start')" in script
    assert "ch_RNA1_QC_FASTP = RNA1_QC_FASTP(abi_root)" in script
    assert "ch_RNA1_ALIGNMENT_STAR = RNA1_ALIGNMENT_STAR(ch_RNA1_QC_FASTP)" in script
    assert (
        "ch_RNA1_EXPRESSION_FEATURECOUNTS = RNA1_EXPRESSION_FEATURECOUNTS(ch_RNA1_ALIGNMENT_STAR)"
    ) in script


def test_nextflow_exporter_smoke_mode_does_not_call_real_tools(tmp_path):
    plugin = get_plugin("metatranscriptomics")
    config = plugin.load_config(overrides={"outdir": str(tmp_path / "results")})
    plan = plugin.build_plan(config)

    script = NextflowExporter().export(plan, config, plugin.registry(), smoke=True)

    assert "// Export mode: smoke" in script
    assert "ABI Nextflow smoke step" in script
    assert "fastp -i" not in script
    assert "STAR --runThreadN" not in script
    assert "featureCounts -T" not in script


def test_nextflow_exporter_writes_script(tmp_path):
    plugin = get_plugin("metatranscriptomics")
    config = plugin.load_config(overrides={"outdir": str(tmp_path / "results")})
    plan = plugin.build_plan(config)
    output = tmp_path / "workflow.nf"

    path = NextflowExporter().write(plan, config, plugin.registry(), output)

    assert path == output
    assert output.exists()
    assert output.read_text(encoding="utf-8").startswith("// Generated by ABI NextflowExporter.")


def test_nextflow_exporter_serializes_metagenomic_plasmid_steps_without_path_edges(tmp_path):
    """Metagenomic plasmid DAG has worker-scoped internal handlers that feed
    external steps — export must fail-fast because Nextflow cannot execute
    those internal handlers."""
    plugin = get_plugin("metagenomic_plasmid")
    config = plugin.load_config(
        "examples/config_minimal.yaml",
        overrides={"outdir": str(tmp_path / "plasmid"), "log_dir": str(tmp_path / "log")},
    )
    plan = plugin.build_plan(config)

    with pytest.raises(ToolError, match="worker-scoped internal handler"):
        NextflowExporter().export(plan, config, plugin.registry())
